- name: Playbook for testing AAP2 Setup
  hosts: webservers
  tasks:
    - name: Reboot loadbalancer
      reboot: 
    - name: Wait 600 seconds for target connection to become reachable/usable
      wait_for_connection:
        timeout: 600
        delay: 0

    - ping:
