- name: Playbook for testing Apache setup
  hosts: webservers
  tasks:
    - name: This task ensures httpd package is present on {{ ansible_hostname }}
      ansible.builtin.uri:
        url: http://{{ ansible_hostname }}
      register: response
      delegate_to: localhost

    - name: Print the response from apache
      ansible.builtin.debug:
        msg: "{{ response.content }}"
      delegate_to: localhost

