- name: Playbook for testing Apache setup
  hosts: webservers
  tasks:
    - name: This task ensures httpd package is present on {{ ansible_fqdn }}
      ansible.builtin.uri:
        url: http://{{ ansible_fqdn }}
      register: response
      delegate_to: localhost

    - name: debug
      ansible.builtin.debug:
        var: response
        
    - name: Print the response from apache
      ansible.builtin.debug:
        msg: "{{ response.content }}"
      delegate_to: localhost

