- name: Apache installer playbook
  hosts: webservers
  tasks:
    - name: This task ensures httpd package is present on {{ ansible_hostname }}
      yum:
        name: httpd
        state: present
      become: true
